import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["500", "600"] });

export const metadata: Metadata = {
  title: "Next.js app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-background ${poppins.className}`}>
        <div className="container mx-auto p-8 mt-[-8px]">{children}</div>
      </body>
    </html>
  );
}
